import { getAllOperations, resolveRef } from '../utils/loader.js';
import { OpenAPISpec } from '../types.js';
import { getFakerCall, generateFakeObject } from './data-faker.js';

/**
 * Generate Vitest TypeScript test files from an OpenAPI spec.
 */
export function generate(spec: OpenAPISpec, options: { baseUrl?: string; tag?: string; output?: string } = {}): Array<{ name: string; content: string }> {
  const ops = getAllOperations(spec);
  const baseUrl = options.baseUrl || 'http://localhost:3000';
  const tagFilter = options.tag || null;

  // Group operations by tag
  const byTag: Record<string, any[]> = {};
  for (const op of ops) {
    const tags = op.operation.tags || ['untagged'];
    for (const tag of tags) {
      if (tagFilter && tag.toLowerCase() !== tagFilter.toLowerCase()) continue;
      if (!byTag[tag]) byTag[tag] = [];
      byTag[tag].push(op);
    }
  }

  const files: Array<{ name: string; content: string }> = [];

  // Generate helper file
  files.push({
    name: 'api-helper.ts',
    content: generateHelper(baseUrl),
  });

  // Generate schema file
  files.push({
    name: 'schemas.ts',
    content: generateSchemas(spec),
  });

  // Generate test file per tag
  for (const [tag, tagOps] of Object.entries(byTag)) {
    const fileName = `${toKebabCase(tag)}.test.ts`;
    const content = generateTestFile(tag, tagOps, spec);
    files.push({ name: fileName, content });
  }

  return files;
}

function generateHelper(baseUrl: string) {
  return `// Auto-generated by swagger-sentinel — do not edit manually
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { faker } from '@faker-js/faker';

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

export const BASE_URL = process.env.API_BASE_URL || '${baseUrl}';

/**
 * Initialize Faker with a seed for consistent data.
 */
export function setSeed(seed: string | number) {
  if (typeof seed === 'string') {
    // Basic string hashing for seeding
    let hash = 0;
    for (let i = 0; i < seed.length; i++) {
      hash = ((hash << 5) - hash) + seed.charCodeAt(i);
      hash |= 0;
    }
    faker.seed(Math.abs(hash));
  } else {
    faker.seed(seed);
  }
}

export async function apiRequest(
  method: string,
  path: string,
  options: {
    body?: any;
    headers?: Record<string, string>;
    query?: Record<string, string>;
  } = {}
) {
  const url = new URL(path, BASE_URL);
  if (options.query) {
    for (const [k, v] of Object.entries(options.query)) {
      url.searchParams.set(k, v);
    }
  }

  const fetchOptions: RequestInit = {
    method,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  };

  if (options.body && method !== 'GET') {
    fetchOptions.body = JSON.stringify(options.body);
  }

  const response = await fetch(url.toString(), fetchOptions);

  let data: any = null;
  const contentType = response.headers.get('content-type') || '';
  if (contentType.includes('application/json')) {
    data = await response.json();
  }

  return {
    status: response.status,
    headers: Object.fromEntries(response.headers.entries()),
    data,
  };
}

export function validateSchema(data: any, schema: object): { valid: boolean; errors: string[] } {
  const validate = ajv.compile(schema);
  const valid = validate(data);
  const errors = (validate as any).errors?.map((e: any) => \`\${e.instancePath} \${e.message}\`) || [];
  return { valid: !!valid, errors };
}

export function randomUUID(): string {
  return faker.string.uuid();
}
`;
}

function generateSchemas(spec: OpenAPISpec) {
  const schemas = spec.components?.schemas || {};
  let content = '// Auto-generated by swagger-sentinel — do not edit manually\n\n';

  for (const [name, schema] of Object.entries(schemas)) {
    content += `export const ${name}Schema = ${JSON.stringify(schemaToJsonSchema(schema, spec), null, 2)} as const;\n\n`;
  }

  return content;
}

function schemaToJsonSchema(schema: any, spec: OpenAPISpec): any {
  if (schema.$ref) {
    const resolved = resolveRef(spec, schema.$ref);
    return resolved ? schemaToJsonSchema(resolved, spec) : {};
  }

  const result = { ...schema };

  // Recursively resolve nested $refs
  if (result.properties) {
    const props: any = {};
    for (const [k, v] of Object.entries(result.properties)) {
      props[k] = schemaToJsonSchema(v, spec);
    }
    result.properties = props;
  }

  if (result.items) {
    result.items = schemaToJsonSchema(result.items, spec);
  }

  return result;
}

function generateTestFile(tag: string, ops: any[], spec: OpenAPISpec) {
  let content = `// Auto-generated by swagger-sentinel — do not edit manually
import { describe, it, expect, beforeEach } from 'vitest';
import { apiRequest, validateSchema, randomUUID, setSeed } from './api-helper';
import { faker } from '@faker-js/faker';
import * as schemas from './schemas';

`;

  for (const op of ops) {
    const { path, method, operation } = op;
    const responses = operation.responses || {};
    const pathParams = (path.match(/\{(\w+)\}/g) || []).map((p: string) => p.replace(/[{}]/g, ''));
    const hasRequestBody = !!operation.requestBody;

    content += `describe('${method} ${path}', () => {\n`;
    content += `  beforeEach(() => {\n`;
    content += `    setSeed('${method}-${path}'); // Ensures consistent data per endpoint\n`;
    content += `  });\n\n`;

    // Generate test for each response code
    for (const [statusCode, response] of Object.entries(responses) as any[]) {
      const status = parseInt(statusCode, 10);
      if (isNaN(status)) continue; // skip 'default'

      const testName = getTestName(method, path, status, response);
      
      content += `  it('${testName}', async () => {\n`;

      // Build request
      let testPath = path;
      for (const param of pathParams) {
        if (status === 404) {
          content += `    const ${param} = randomUUID(); // non-existent\n`;
        } else {
          // Try to find schema for parameter
          const paramDef = (operation.parameters || []).find((p: any) => p.in === 'path' && p.name === param);
          const fakerCall = paramDef ? getFakerCall(param, paramDef.schema || {}) : `faker.lorem.word()`;
          content += `    const ${param} = ${fakerCall};\n`;
        }
        testPath = testPath.replace(`{${param}}`, `\${${param}}`);
      }

      // Headers
      const headerParams = (operation.parameters || []).filter((p: any) => p.in === 'header' && p.required);
      const headers: any = {};
      for (const hp of headerParams) {
        const fakerCall = getFakerCall(hp.name, hp.schema || {});
        headers[hp.name] = `\${${fakerCall}}`;
      }

      const headersStr = Object.keys(headers).length > 0
        ? `, { headers: { ${Object.entries(headers).map(([k, v]) => `'${k}': \`${v}\``).join(', ')} } }`
        : '';

      if (hasRequestBody && status < 400) {
        let bodySchema = operation.requestBody.content?.['application/json']?.schema;
        if (bodySchema?.$ref) bodySchema = resolveRef(spec, bodySchema.$ref);
        
        const bodyContent = bodySchema ? generateFakeObject(bodySchema, spec) : '{}';
        content += `    const body = ${bodyContent};\n`;
        content += `    const response = await apiRequest('${method}', \`${testPath}\`${headersStr ? `, { ...${headersStr.replace(', {', '{')}, body }` : ', { body }'});\n`;
      } else {
        content += `    const response = await apiRequest('${method}', \`${testPath}\`${headersStr});\n`;
      }

      content += `\n`;
      content += `    expect(response.status).toBe(${status});\n`;

      // Schema validation for responses with content
      const respContent = response.content;
      if (respContent) {
        const jsonContent = respContent['application/json'];
        if (jsonContent?.schema?.$ref) {
          const schemaName = jsonContent.schema.$ref.split('/').pop();
          content += `    const { valid, errors } = validateSchema(response.data, schemas.${schemaName}Schema);\n`;
          content += `    expect(valid, \`Schema errors: \${errors.join(', ')}\`).toBe(true);\n`;
        }
      }

      // Check response headers
      if (response.headers) {
        for (const headerName of Object.keys(response.headers)) {
          content += `    expect(response.headers).toHaveProperty('${headerName.toLowerCase()}');\n`;
        }
      }

      content += `  });\n\n`;
    }

    content += `});\n\n`;
  }

  return content;
}

function getTestName(method: string, path: string, status: number, response: any) {
  if (status >= 200 && status < 300) {
    return `should return ${status} on successful ${method.toLowerCase()} request`;
  }
  if (status === 400) return 'should return 400 for invalid request';
  if (status === 401) return 'should return 401 without authentication';
  if (status === 403) return 'should return 403 without authorization';
  if (status === 404) return 'should return 404 for non-existent resource';
  if (status === 409) return 'should return 409 on conflict';
  if (status === 413) return 'should return 413 when payload too large';
  if (status === 429) return 'should return 429 when rate limited';
  
  const desc = response.description || '';
  return `should return ${status} — ${desc.substring(0, 50)}`;
}

function toKebabCase(str: string) {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .toLowerCase()
    .replace(/^-|-$/g, '');
}
