import type { ValidationResult } from "../types.js";

/**
 * Detect if running in GitHub Actions
 */
export function isGitHubActions(): boolean {
	return process.env.GITHUB_ACTIONS === "true";
}

/**
 * Format a validation result as a GitHub Action annotation command
 */
export function formatGitHubAnnotation(
	result: ValidationResult,
	filePath: string,
): string {
	if (result.passed) return "";

	const severity = result.severity === "error" ? "error" : "warning";
	const line = result.line || 1;
	const message = `[${result.id}] ${result.message}${result.details ? ` - ${result.details}` : ""}`;

	// Format: ::error file={name},line={line},col={col}::{message}
	return `::${severity} file=${filePath},line=${line}::${message}`;
}

/**
 * Generate a Markdown summary for the GitHub Job Summary
 */
export function generateGitHubSummary(
	results: ValidationResult[],
	specFile: string,
): string {
	const total = results.length;
	const passed = results.filter((r) => r.passed).length;
	const failed = results.filter((r) => !r.passed).length;
	const errors = results.filter(
		(r) => !r.passed && r.severity === "error",
	).length;
	const warnings = results.filter(
		(r) => !r.passed && r.severity === "warning",
	).length;
	const suggestions = results.filter(
		(r) => !r.passed && r.severity === "suggestion",
	).length;

	const passRate = total > 0 ? ((passed / total) * 100).toFixed(1) : "0";
	const statusIcon = errors === 0 ? "✅" : "❌";

	let md = `### ${statusIcon} Swagger Sentinel Report: \`${specFile}\`\n\n`;

	md += `| Metric | Count | Rate |\n`;
	md += `| :--- | :--- | :--- |\n`;
	md += `| **Total Checks** | ${total} | -- |\n`;
	md += `| **Passed** | ${passed} | ${passRate}% |\n`;
	md += `| **Errors** | ${errors} | -- |\n`;
	md += `| **Warnings** | ${warnings} | -- |\n`;
	md += `| **Suggestions** | ${suggestions} | -- |\n\n`;

	if (failed > 0) {
		md += `#### 📋 Issues Found\n\n`;
		md += `| ID | Severity | Category | Message |\n`;
		md += `| :--- | :--- | :--- | :--- |\n`;

		results
			.filter((r) => !r.passed)
			.slice(0, 50)
			.forEach((r) => {
				const icon =
					r.severity === "error"
						? "🔴"
						: r.severity === "warning"
							? "🟡"
							: "🔵";
				md += `| ${r.id} | ${icon} ${r.severity} | ${r.category} | ${r.message} |\n`;
			});

		if (failed > 50) {
			md += `\n> *Showing first 50 of ${failed} issues. Check logs for full details.*\n`;
		}
	} else {
		md += `\n✨ **Perfect Score!** All automated checks passed successfully.\n`;
	}

	md += `\n---\n*Generated by [swagger-sentinel](https://github.com/mustafasercansak/swagger-sentinel)*`;

	return md;
}
