// Auto-generated by swagger-sentinel — do not edit manually
import Ajv from 'ajv';
import addFormats from 'ajv-formats';

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

export const BASE_URL = process.env.API_BASE_URL || 'http://localhost:3000';

export async function apiRequest(
  method: string,
  path: string,
  options: {
    body?: any;
    headers?: Record<string, string>;
    query?: Record<string, string>;
  } = {}
) {
  const url = new URL(path, BASE_URL);
  if (options.query) {
    for (const [k, v] of Object.entries(options.query)) {
      url.searchParams.set(k, v);
    }
  }

  const fetchOptions: RequestInit = {
    method,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  };

  if (options.body && method !== 'GET') {
    fetchOptions.body = JSON.stringify(options.body);
  }

  const response = await fetch(url.toString(), fetchOptions);

  let data: any = null;
  const contentType = response.headers.get('content-type') || '';
  if (contentType.includes('application/json')) {
    data = await response.json();
  }

  return {
    status: response.status,
    headers: Object.fromEntries(response.headers.entries()),
    data,
  };
}

export function validateSchema(data: any, schema: object): { valid: boolean; errors: string[] } {
  const validate = ajv.compile(schema);
  const valid = validate(data);
  const errors = validate.errors?.map(e => `${e.instancePath} ${e.message}`) || [];
  return { valid: !!valid, errors };
}

export function randomUUID(): string {
  return crypto.randomUUID();
}
