// Auto-generated by swagger-sentinel — do not edit manually
import { describe, it, expect } from 'vitest';
import { apiRequest, validateSchema, randomUUID } from './api-helper';
import * as schemas from './schemas';

describe('GET /api/v1/pets', () => {
  it('should return 200 on successful get request', async () => {
    const response = await apiRequest('GET', `/api/v1/pets`);

    expect(response.status).toBe(200);
  });

});

describe('POST /api/v1/pets', () => {
  it('should return 201 on successful post request', async () => {
    // TODO: provide valid request body
    const body = {};
    const response = await apiRequest('POST', `/api/v1/pets`, { body });

    expect(response.status).toBe(201);
    const { valid, errors } = validateSchema(response.data, schemas.PetSchema);
    expect(valid, `Schema errors: ${errors.join(', ')}`).toBe(true);
  });

  it('should return 400 for invalid request', async () => {
    const response = await apiRequest('POST', `/api/v1/pets`);

    expect(response.status).toBe(400);
    const { valid, errors } = validateSchema(response.data, schemas.ErrorResponseSchema);
    expect(valid, `Schema errors: ${errors.join(', ')}`).toBe(true);
  });

});

describe('GET /api/v1/pets/{petId}', () => {
  it('should return 200 on successful get request', async () => {
    const petId = 'test-petId'; // TODO: replace with valid value
    const response = await apiRequest('GET', `/api/v1/pets/${petId}`);

    expect(response.status).toBe(200);
    const { valid, errors } = validateSchema(response.data, schemas.PetSchema);
    expect(valid, `Schema errors: ${errors.join(', ')}`).toBe(true);
  });

  it('should return 404 for non-existent resource', async () => {
    const petId = randomUUID(); // non-existent
    const response = await apiRequest('GET', `/api/v1/pets/${petId}`);

    expect(response.status).toBe(404);
    const { valid, errors } = validateSchema(response.data, schemas.ErrorResponseSchema);
    expect(valid, `Schema errors: ${errors.join(', ')}`).toBe(true);
  });

});

describe('DELETE /api/v1/pets/{petId}', () => {
  it('should return 204 on successful delete request', async () => {
    const petId = 'test-petId'; // TODO: replace with valid value
    const response = await apiRequest('DELETE', `/api/v1/pets/${petId}`);

    expect(response.status).toBe(204);
  });

});

