// Auto-generated by swagger-sentinel — do not edit manually

export const PetSchema = {
  "type": "object",
  "required": [
    "id",
    "name",
    "species"
  ],
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
    },
    "name": {
      "type": "string",
      "example": "Buddy"
    },
    "species": {
      "type": "string",
      "enum": [
        "dog",
        "cat",
        "bird",
        "fish"
      ],
      "example": "dog"
    },
    "age": {
      "type": "integer",
      "example": 3
    },
    "createdAt": {
      "type": "string",
      "format": "date-time"
    }
  }
} as const;

export const ErrorResponseSchema = {
  "type": "object",
  "required": [
    "code",
    "message"
  ],
  "properties": {
    "code": {
      "type": "string",
      "example": "NOT_FOUND"
    },
    "message": {
      "type": "string",
      "example": "Resource not found"
    }
  }
} as const;

