import type { RuleDefinition } from "./types.js";

export const RULE_REGISTRY: RuleDefinition[] = [
	// --- Structure & Metadata ---
	{
		id: "S01",
		category: "Structure",
		title: "Info block includes contact",
		description: "API info block should include contact name/email/url",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "S02",
		category: "Structure",
		title: "Version follows semver",
		description: "API version should follow semantic versioning (x.y.z)",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "S03",
		category: "Structure",
		title: "Servers array defined",
		description:
			"The servers array should be defined to help client generation",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "S04",
		category: "Structure",
		title: "At least one path defined",
		description: "The API must have at least one valid path",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "S05",
		category: "Structure",
		title: "OpenAPI version 3.0.x or 3.1.x",
		description: "The spec should use OpenAPI 3.0.x or 3.1.x",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "S06",
		category: "Structure",
		title: "Info has description",
		description: "API info block should have a descriptive description field",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "S07",
		category: "Structure",
		title: "License specified",
		description: "The API should include license information",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "S08",
		category: "Structure",
		title: "Title is descriptive",
		description: "The API title should be more than 3 characters long",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "S09",
		category: "Structure",
		title: "External docs link provided",
		description: "Consider providing external documentation for the API",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "S10",
		category: "Structure",
		title: "Components exist when $ref used",
		description: "If $ref is used, the components section should exist",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "S11",
		category: "Structure",
		title: "Terms of service URL specified",
		description: "Terms of Service URL should be provided",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "S12",
		category: "Structure",
		title: "API categorization is appropriate",
		description: "The API follows a logical domain boundary",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "S13",
		category: "Structure",
		title: "API lifecycle state documented",
		description: "Alpha/Beta/Stable state is clear to users",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "S14",
		category: "Structure",
		title: "Deprecation policy defined",
		description: "How long are deprecated versions supported?",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "S15",
		category: "Structure",
		title: "Breaking change notification policy",
		description: "How will users be notified of breaking changes?",
		severity: "warning",
		isAutomated: false,
	},

	// --- Path Design ---
	{
		id: "P15",
		category: "Paths",
		title: "Paths use kebab-case",
		description: "Path segments should use kebab-case (lowercase with hyphens)",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "P16",
		category: "Paths",
		title: "No trailing slashes",
		description: "Paths should not end with a trailing slash",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "P17",
		category: "Paths",
		title: "Plural resource naming",
		description:
			"Resource names should be plural nouns (e.g. /users, not /user)",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "P18",
		category: "Paths",
		title: "Nesting ≤ 3 levels",
		description: "Path nesting depth should not exceed 3 levels",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "P19",
		category: "Paths",
		title: "Versioning present",
		description: "API version should be present in path or server URL",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "P20",
		category: "Paths",
		title: "No file extensions",
		description: "Paths should not include file extensions like .json or .xml",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "P21",
		category: "Paths",
		title: "Consistent prefix",
		description: "All paths should share a consistent foundational prefix",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "P22",
		category: "Paths",
		title: "No empty segments",
		description: "Paths should not contain double slashes or empty segments",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "P23",
		category: "Paths",
		title: "Path params documented",
		description:
			"All path parameters must be defined in the parameters section",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "P24",
		category: "Paths",
		title: "No HTTP verb names in paths",
		description:
			"Path segments should not contain HTTP verb names (get, post, delete)",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "P25",
		category: "Paths",
		title: "Path param casing",
		description:
			"Path parameter names should use consistent casing (snake_case/camelCase)",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "P26",
		category: "Paths",
		title: "No sensitive keywords in paths",
		description:
			"Path parameters should not contain tokens, keys, or passwords",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "P27",
		category: "Paths",
		title: "No trailing dots",
		description: "Path segments should not end with a dot",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "P28",
		category: "Paths",
		title: "Resource abstraction",
		description:
			"The level of resource abstraction is appropriate for the domain",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "P29",
		category: "Paths",
		title: "Intuitive naming",
		description: "Resource names are intuitive and domain-specific",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "P30",
		category: "Paths",
		title: "No internal leakage",
		description: "No leakage of internal database IDs or structures",
		severity: "error",
		isAutomated: false,
	},
	{
		id: "P31",
		category: "Paths",
		title: "HATEOAS implementation",
		description: "Hypermedia links used where appropriate",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "P32",
		category: "Paths",
		title: "Path vs Query",
		description:
			"Path params used for direct access, query params for filters/sorts",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "P33",
		category: "Paths",
		title: "URL length limits",
		description: "URLs are within standard browser/server limits (<2000 chars)",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "P34",
		category: "Paths",
		title: "Canonical URLs",
		description: "Canonical URLs defined for duplicated resources",
		severity: "suggestion",
		isAutomated: false,
	},

	// --- Operations ---
	{
		id: "O31",
		category: "Operations",
		title: "operationId required",
		description: "Every operation should have a unique operationId",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "O31b",
		category: "Operations",
		title: "operationIds are unique",
		description: "Each operationId must be unique across the entire spec",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "O32",
		category: "Operations",
		title: "POST returns 201/202",
		description:
			"Success responses for POST should usually be 201 Created or 202 Accepted",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "O33",
		category: "Operations",
		title: "DELETE returns 204",
		description: "Successful DELETE operations should return 204 No Content",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "O34",
		category: "Operations",
		title: "Operations tagged",
		description: "Every operation should be assigned at least one tag",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "O35",
		category: "Operations",
		title: "Pagination support",
		description: "List operations should support pagination parameters",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "O36",
		category: "Operations",
		title: "Summary/Description present",
		description: "All operations should have a summary or description",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "O37",
		category: "Operations",
		title: "PUT/PATCH have body",
		description: "PUT and PATCH operations should define a requestBody",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "O38",
		category: "Operations",
		title: "Prefer body for mutations",
		description:
			"POST/PUT mutations should prefer requestBody over query parameters",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "O39",
		category: "Operations",
		title: "HEAD for GET",
		description: "A HEAD method should be defined wherever a GET method exists",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "O40",
		category: "Operations",
		title: "PATCH content types",
		description: "PATCH operations should use JSON merge-patch or JSON-patch",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "O41",
		category: "Operations",
		title: "No verb redundant prefix",
		description: "operationIds should not redundancies the HTTP method",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "O42",
		category: "Operations",
		title: "GET has no requestBody",
		description: "GET operations do not support request bodies",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "O43",
		category: "Operations",
		title: "429 rate-limit headers",
		description: "429 responses should include rate-limit or retry headers",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "O44",
		category: "Operations",
		title: "202 polling headers",
		description:
			"202 Accepted should include Location or Link for status polling",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "O45",
		category: "Operations",
		title: "Idempotence respected",
		description: "Idempotence logic is followed for PUT and DELETE",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "O46",
		category: "Operations",
		title: "Safe methods read-only",
		description: "GET and HEAD methods are strictly read-only",
		severity: "error",
		isAutomated: false,
	},
	{
		id: "O47",
		category: "Operations",
		title: "Atomic bulk operations",
		description:
			"Bulk operations provide atomic guarantees or clear error mapping",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "O48",
		category: "Operations",
		title: "Async callbacks/polling",
		description: "Long-running operations provide status polling or callbacks",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "O49",
		category: "Operations",
		title: "CORS configuration",
		description: "CORS preflight (OPTIONS) is correctly configured",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "O50",
		category: "Operations",
		title: "Logical state transitions",
		description:
			"Resource state transitions are logical and reflected in status codes",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "O51",
		category: "Operations",
		title: "Method overrides",
		description:
			"Method overrides (X-HTTP-Method-Override) are supported with caution",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "O52",
		category: "Operations",
		title: "Health check endpoints",
		description: "Basic health/status monitoring endpoints are provided",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "O53",
		category: "Operations",
		title: "Telemetry standards",
		description: "Monitoring/Metrics endpoints follow industry standards",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "O54",
		category: "Operations",
		title: "Request correlation",
		description: "Correlation IDs (X-Request-ID) are supported",
		severity: "suggestion",
		isAutomated: false,
	},

	// --- Request Validation ---
	{
		id: "R50",
		category: "Request",
		title: "Strings have maxLength",
		description: "String parameters should have a maxLength defined",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R51",
		category: "Request",
		title: "Numbers have range",
		description: "Numeric parameters should have minimum/maximum defined",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R52",
		category: "Request",
		title: "Arrays have maxItems",
		description: "Array parameters should have maxItems defined",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R53",
		category: "Request",
		title: "Required fields defined",
		description: "Request body schemas should specify required fields",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R54",
		category: "Request",
		title: "Content-type required",
		description: "All request bodies must specify a content-type",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "R55",
		category: "Request",
		title: "Enum consistent casing",
		description: "Enum values should use consistent casing",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R56",
		category: "Request",
		title: "Param descriptions",
		description: "All parameters must have a description",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R57",
		category: "Request",
		title: "Semantic format keywords",
		description:
			"Fields with semantic names (email, uuid) should have matching formats",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "R58",
		category: "Request",
		title: "Binary in multipart",
		description: "Binary upload fields should use multipart/form-data",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R59",
		category: "Request",
		title: "ID parameter formats",
		description:
			"ID parameters should define a specific format (uuid) or pattern",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R60",
		category: "Request",
		title: "Large body maxProperties",
		description: "Large request body objects should define maxProperties",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "R61",
		category: "Request",
		title: "No sensitive examples",
		description:
			"Sensitive fields (password/token) should not include example values",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R62",
		category: "Request",
		title: "Regex pattern testing",
		description: "Complex regex patterns are thoroughly documented",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "R63",
		category: "Request",
		title: "Business logic docs",
		description: "Custom business logic validation beyond schema is documented",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "R64",
		category: "Request",
		title: "Client retry policies",
		description: "Timeouts and retry policies are suggested in docs",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "R65",
		category: "Request",
		title: "File upload strategy",
		description: "Large file upload strategy (multipart vs chunked) is clear",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "R66",
		category: "Request",
		title: "Input sanitization",
		description: "Descriptions address input sanitization (XSS/SQLi)",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "R67",
		category: "Request",
		title: "Recursion depth",
		description: "Recursive objects have appropriate depth constraints",
		severity: "error",
		isAutomated: false,
	},

	// --- Response Design ---
	{
		id: "R70",
		category: "Response",
		title: "Consistent error schema",
		description:
			"Error responses should use a consistent schema across the API",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R71",
		category: "Response",
		title: "4xx have body",
		description: "All client error responses must include a response body",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R72",
		category: "Response",
		title: "5xx defined",
		description: "5xx or default error responses should be defined",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "R73",
		category: "Response",
		title: "Operations have responses",
		description: "Every operation must define at least one response",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "R74",
		category: "Response",
		title: "Success body content",
		description: "Success responses (except 204) should define content",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R75",
		category: "Response",
		title: "429 rate-limit headers",
		description: "429 responses must include rate-limit headers",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R76",
		category: "Response",
		title: "Schemas define required",
		description: "All schemas should specify required fields",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "R77",
		category: "Response",
		title: "201 Location header",
		description: "201 Created responses should include a Location header",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "R78",
		category: "Response",
		title: "List total count",
		description:
			"List responses should include a total count (header or wrapper)",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "R79",
		category: "Response",
		title: "Single-resource ETag",
		description: "Single-resource GETs should define ETag or Last-Modified",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "R80",
		category: "Response",
		title: "406 defined",
		description:
			"Operations with multiple content types should define 406 Not Acceptable",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "R81",
		category: "Response",
		title: "415 defined",
		description:
			"Operations with request bodies should define 415 Unsupported Media Type",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "R82",
		category: "Response",
		title: "Content negotiation",
		description: "The Accept header is strictly respected by the API",
		severity: "error",
		isAutomated: false,
	},
	{
		id: "R83",
		category: "Response",
		title: "Discoverability links",
		description: "Link headers provided for resource discoverability",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "R84",
		category: "Response",
		title: "Partial content support",
		description: "206 Partial Content supported for large resource downloads",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "R85",
		category: "Response",
		title: "Compression support",
		description: "Gzip/Brotli supported for text-rich responses",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "R86",
		category: "Response",
		title: "Caching strategy",
		description: "Cache-Control headers used effectively for static data",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "R87",
		category: "Response",
		title: "Localized errors",
		description: "Error messages are localized or support i18n",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "R88",
		category: "Response",
		title: "Masked debug info",
		description: "Sensitive data/traces are masked in productive logs",
		severity: "error",
		isAutomated: false,
	},
	{
		id: "R89",
		category: "Response",
		title: "Field selection",
		description: "Sparse fieldsets supported via query parameters",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "R90",
		category: "Response",
		title: "Filtering/Sorting standard",
		description: "Filtering/sorting syntax follows a cross-API standard",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "R91",
		category: "Response",
		title: "ISO 8601 formatting",
		description: "All dates follow ISO 8601 strictly",
		severity: "error",
		isAutomated: false,
	},
	{
		id: "R92",
		category: "Response",
		title: "Precise currency",
		description: "Money/Currency values handled with decimal precision",
		severity: "error",
		isAutomated: false,
	},
	{
		id: "R93",
		category: "Response",
		title: "Explicit discriminators",
		description: "oneOf/anyOf schemas use explicit discriminators",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "R94",
		category: "Response",
		title: "Binary dispositions",
		description: "Binary data returned with correct Content-Disposition",
		severity: "warning",
		isAutomated: false,
	},

	// --- Security ---
	{
		id: "SEC90",
		category: "Security",
		title: "Security schemes defined",
		description: "API security schemes (Auth) must be defined",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "SEC91",
		category: "Security",
		title: "No API keys in query",
		description: "API keys must not be passed as query parameters",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "SEC93",
		category: "Security",
		title: "Sensitive fields writeOnly",
		description: "Sensitive fields like passwords must be marked writeOnly",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "SEC94",
		category: "Security",
		title: "Security applied",
		description:
			"Security requirements should be applied globally or per-operation",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "SEC95",
		category: "Security",
		title: "HTTPS production",
		description: "Production server URLs must use the HTTPS protocol",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "SEC96",
		category: "Security",
		title: "OAuth2 scopes defined",
		description: "OAuth2 flows must define at least one scope",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "SEC97",
		category: "Security",
		title: "Secured op defines 401",
		description: "Secured operations should define a 401 Unauthorized response",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "SEC98",
		category: "Security",
		title: "Secured op defines 403",
		description: "Secured operations should define a 403 Forbidden response",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "SEC99",
		category: "Security",
		title: "No credentials in URL",
		description: "Credentials must not be embedded directly in server URLs",
		severity: "error",
		isAutomated: true,
	},
	{
		id: "SEC100",
		category: "Security",
		title: "No HTTP Basic auth",
		description: "Standard HTTP Basic authentication should not be used",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "SEC101",
		category: "Security",
		title: "No X- prefix",
		description:
			"Custom security headers should not use the deprecated X- prefix",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "SEC102",
		category: "Security",
		title: "CSP for HTML",
		description:
			"HTML responses should include a Content-Security-Policy header",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "SEC103",
		category: "Security",
		title: "CORS restrictive",
		description: "CORS headers are restrictive by default",
		severity: "error",
		isAutomated: false,
	},
	{
		id: "SEC104",
		category: "Security",
		title: "Token rotation docs",
		description: "JWT/Token rotation/expiry clearly documented",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "SEC105",
		category: "Security",
		title: "mTLS verification",
		description: "mTLS considered for high-security service-to-service",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "SEC106",
		category: "Security",
		title: "HSTS header",
		description: "HSTS (Strict-Transport-Security) header recommended",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "SEC107",
		category: "Security",
		title: "Key rotation mechanism",
		description: "Mechanism for API key rotation exists",
		severity: "warning",
		isAutomated: false,
	},

	// --- Documentation ---
	{
		id: "DOC110",
		category: "Documentation",
		title: "Param descriptions",
		description: "All parameters must have a description",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "DOC112",
		category: "Documentation",
		title: "Schema examples",
		description: "Schemas should include representative example values",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "DOC115",
		category: "Documentation",
		title: "Deprecated sunset date",
		description: "Deprecated operations should have an x-sunset-date",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "DOC116",
		category: "Documentation",
		title: "Tag descriptions",
		description: "Tags used by operations should have descriptions",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "DOC117",
		category: "Documentation",
		title: "Response examples",
		description: "Operations should include at least one response example",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "DOC118",
		category: "Documentation",
		title: "Request body examples",
		description: "Request bodies should include an example",
		severity: "suggestion",
		isAutomated: true,
	},
	{
		id: "DOC119",
		category: "Documentation",
		title: "Title/Desc length",
		description:
			"API info block should have a detailed description (>20 chars)",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "DOC120",
		category: "Documentation",
		title: "Prop descriptions",
		description: "All schema properties should have their own descriptions",
		severity: "warning",
		isAutomated: true,
	},
	{
		id: "DOC121",
		category: "Documentation",
		title: "Changelog maintained",
		description: "A changelog or release notes file is maintained",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "DOC122",
		category: "Documentation",
		title: "Migration guide",
		description: "Migration guide provided for breaking changes",
		severity: "warning",
		isAutomated: false,
	},
	{
		id: "DOC123",
		category: "Documentation",
		title: "Postman collections",
		description: "Postman or Insomnia collections available for download",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "DOC124",
		category: "Documentation",
		title: "Dev Tutorial",
		description: "Quickstart guide exists for new developers",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "DOC125",
		category: "Documentation",
		title: "Code snippets",
		description: "Sample code snippets provided in multiple languages",
		severity: "suggestion",
		isAutomated: false,
	},
	{
		id: "DOC126",
		category: "Documentation",
		title: "Official SDKs",
		description: "SDKs are available for major platforms",
		severity: "warning",
		isAutomated: false,
	},
];

export function getRule(id: string) {
	return RULE_REGISTRY.find((r) => r.id === id);
}

export function getAutomatedRules() {
	return RULE_REGISTRY.filter((r) => r.isAutomated);
}

export function getRulesByCategory(category: string) {
	return RULE_REGISTRY.filter(
		(r) => r.category.toLowerCase() === category.toLowerCase(),
	);
}

export function getRuleExtendedInfo(id: string) {
	const rule = getRule(id);
	if (!rule) return null;
	return `
[${rule.id}] ${rule.title}
Category: ${rule.category}
Severity: ${rule.severity}
Automated: ${rule.isAutomated ? "Yes" : "No (Requires specialized tools or human review)"}

Description:
${rule.description}
  `.trim();
}
